name = input('이름을 입력하세요 : ')
std_id = int(input('학번을 입력하세요 : '))
std_st = input('학과를 입력하세요 : ')
sds = input('학년을 입력하세요 : ')
sd = input('학교를 입력하세요 : ')

print('<출력>')
print('이름 : ',name)
print('학번 : ',std_id)
print('학과 : ',std_st)
print('학년 : ',sds)
print('학교 : ',sd)
